<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Create inventory_id_format_part table (Custom ID format parts).
 *
 * IMPORTANT:
 * - Do NOT touch other tables/sequences here (inventories/users/messenger/etc).
 * - This migration must be idempotent regarding the existing schema history.
 */
final class Version20251227102113 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create inventory_id_format_part table for Custom ID format parts';
    }

    public function up(Schema $schema): void
    {
        // 1) Core table: inventory_id_format_part
        // Use IDENTITY to avoid manual sequences and to align with our previous migrations.
        $this->addSql("
            CREATE TABLE inventory_id_format_part (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                inventory_id INT NOT NULL,
                position INT NOT NULL,
                type VARCHAR(10) NOT NULL,
                param1 VARCHAR(50) DEFAULT NULL,
                param2 VARCHAR(50) DEFAULT NULL,
                PRIMARY KEY (id)
            )
        ");

        // 2) FK -> inventories (cascade on delete to prevent orphan configuration)
        $this->addSql("
            ALTER TABLE inventory_id_format_part
            ADD CONSTRAINT fk_inventory_id_format_part_inventory
            FOREIGN KEY (inventory_id)
            REFERENCES inventories (id)
            ON DELETE CASCADE
        ");

        // 3) Required invariant: only one part per position per inventory
        $this->addSql("
            CREATE UNIQUE INDEX uniq_inventory_format_position
            ON inventory_id_format_part (inventory_id, position)
        ");

        // 4) Helpful index for lookups by inventory (not strictly required, but cheap & useful)
        $this->addSql("
            CREATE INDEX idx_inventory_id_format_part_inventory
            ON inventory_id_format_part (inventory_id)
        ");
    }

    public function down(Schema $schema): void
    {
        // Drop table is enough: indexes + FK are dropped automatically with it.
        $this->addSql('DROP TABLE inventory_id_format_part');
    }
}
