<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Initial migration.
 *
 * Creates base domain tables only.
 */
final class Version20251226160813 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial migration: users table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("
            CREATE TABLE users (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                email VARCHAR(180) NOT NULL,
                roles JSONB NOT NULL DEFAULT '[]',
                password VARCHAR(255) NOT NULL,
                theme VARCHAR(10) NOT NULL DEFAULT 'light',
                locale VARCHAR(10) NOT NULL DEFAULT 'en',
                PRIMARY KEY (id)
            )
        ");

        $this->addSql('CREATE UNIQUE INDEX uniq_users_email ON users (email)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE users');
    }
}
