<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Inventory items.
 */
final class Version20251226165506 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create inventory_items table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("
            CREATE TABLE inventory_items (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                inventory_id INT NOT NULL,
                custom_id VARCHAR(255) NOT NULL,
                version INT NOT NULL DEFAULT 1,
                PRIMARY KEY (id)
            )
        ");

        $this->addSql('
            ALTER TABLE inventory_items
            ADD CONSTRAINT fk_inventory_item_inventory
            FOREIGN KEY (inventory_id)
            REFERENCES inventories (id)
            ON DELETE CASCADE
        ');

        $this->addSql('
            CREATE UNIQUE INDEX uniq_inventory_custom_id
            ON inventory_items (inventory_id, custom_id)
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE inventory_items');
    }
}
