<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Inventory domain tables.
 */
final class Version20251226163604 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create inventories table';
    }

    public function up(Schema $schema): void
    {
        // inventories
        $this->addSql("
            CREATE TABLE inventories (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                owner_id INT NOT NULL,
                name VARCHAR(255) NOT NULL,
                is_public BOOLEAN NOT NULL,
                version INT NOT NULL DEFAULT 1,
                PRIMARY KEY (id)
            )
        ");

        $this->addSql('CREATE INDEX idx_inventory_is_public ON inventories (is_public)');
        $this->addSql('CREATE INDEX idx_inventory_owner ON inventories (owner_id)');

        $this->addSql('
            ALTER TABLE inventories
            ADD CONSTRAINT fk_inventory_owner
            FOREIGN KEY (owner_id)
            REFERENCES users (id)
            ON DELETE CASCADE
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE inventories');
    }
}
