<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251228170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Fix custom_fields.id generation (PostgreSQL IDENTITY)';
    }

    public function up(Schema $schema): void
    {
        // Добавляем IDENTITY только если его ещё нет (безопасно при повторных запусках).
        $this->addSql("
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema='public'
      AND table_name='custom_fields'
      AND column_name='id'
      AND is_identity='YES'
  ) THEN
    ALTER TABLE custom_fields
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;
        ");
    }

    public function down(Schema $schema): void
    {
        // Обычно down для identity не критичен, но можно убрать:
        $this->addSql("
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema='public'
      AND table_name='custom_fields'
      AND column_name='id'
      AND is_identity='YES'
  ) THEN
    ALTER TABLE custom_fields
      ALTER COLUMN id DROP IDENTITY IF EXISTS;
  END IF;
END $$;
        ");
    }
}
