<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Create inventory_sequence table (Custom ID SEQ counter).
 *
 * Rules:
 * - One sequence per inventory
 * - Safe for SELECT ... FOR UPDATE
 * - No touching unrelated tables
 */
final class Version20251227103441 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create inventory_sequence table for Custom ID generation';
    }

    public function up(Schema $schema): void
    {
        // Core table
        $this->addSql("
            CREATE TABLE inventory_sequence (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                inventory_id INT NOT NULL,
                next_value INT NOT NULL,
                PRIMARY KEY (id)
            )
        ");

        // Enforce 1:1 relation with inventory
        $this->addSql("
            CREATE UNIQUE INDEX uniq_inventory_sequence
            ON inventory_sequence (inventory_id)
        ");

        // FK with cascade delete
        $this->addSql("
            ALTER TABLE inventory_sequence
            ADD CONSTRAINT fk_inventory_sequence_inventory
            FOREIGN KEY (inventory_id)
            REFERENCES inventories (id)
            ON DELETE CASCADE
        ");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE inventory_sequence');
    }
}
