<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Inventory ACL table.
 */
final class Version20251226164529 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create inventory_access table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("
            CREATE TABLE inventory_access (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                inventory_id INT NOT NULL,
                user_id INT NOT NULL,
                permission VARCHAR(10) NOT NULL,
                PRIMARY KEY (id)
            )
        ");

        $this->addSql('
            ALTER TABLE inventory_access
            ADD CONSTRAINT fk_inventory_access_inventory
            FOREIGN KEY (inventory_id)
            REFERENCES inventories (id)
            ON DELETE CASCADE
        ');

        $this->addSql('
            ALTER TABLE inventory_access
            ADD CONSTRAINT fk_inventory_access_user
            FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE
        ');

        $this->addSql('
            CREATE UNIQUE INDEX uniq_inventory_user
            ON inventory_access (inventory_id, user_id)
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE inventory_access');
    }
}
